---
- name: Install and configure Prometheus with Grafana as systemd service
  hosts: prometheus_server
  gather_facts: no
  become: yes

  vars:
    prometheus_version: '2.18.1'
    prometheus_data_dir: '/opt/prometheus'
    prometheus_config_dir: '/etc/prometheus'

  tasks:

    - name: Ensure "prometheus" system group exists
      group:
        name: prometheus
        system: true
        state: present

    - name: Ensure "prometheus" system user exists
      user:
        name: prometheus
        group: prometheus
        system: true
        shell: /sbin/nologin
        create_home: false
        home: "{{ prometheus_data_dir }}"

    - name: Create prometheus data directory
      file:
        path: "{{ prometheus_data_dir }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: 0755

    - name: Create prometheus configuration directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: prometheus
        mode: 0770
      loop:
        - "{{ prometheus_config_dir }}"
        - "{{ prometheus_config_dir }}/conf.d"
        - "{{ prometheus_config_dir }}/file_sd"
        - "{{ prometheus_config_dir }}/rules"

    - name: Download and unarchive Prometheus (Skip when already exists!)
      unarchive:
        src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
        dest: "{{ prometheus_data_dir }}"
        extra_opts: [--strip-components=1]
        remote_src: yes
        creates: "{{ prometheus_data_dir }}/prometheus"

    - name: Configure Prometheus as systemd service
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: 0644
      notify: "Restart Prometheus service"

    - name: Setting Prometheus monitoring parameters
      template:
        src: prometheus.config.j2
        dest: "{{ prometheus_config_dir }}/prometheus.yml"
        owner: root
        group: prometheus
        mode: 0640
        validate: "{{ prometheus_data_dir }}/promtool check config %s"
      notify: "Reload Prometheus service"

    - name: Install required system packages for Grafana
      apt:
        name:
          - 'apt-transport-https'
          - 'gnupg-agent'
          - 'software-properties-common'
        state: present
        update_cache: yes

    - name: Import the official Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Import the Grafana DEB repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Grafana
      apt:
        name: 'grafana'
        state: present
        update_cache: yes
      notify: "Start and enable Grafana service"

  handlers:
    - name: "Restart Prometheus service"
      systemd:
        daemon_reload: yes
        name: prometheus.service
        enabled: yes
        state: restarted

    - name: "Reload Prometheus service"
      systemd:
        name: prometheus.service
        state: reloaded

    - name: "Start and enable Grafana service"
      systemd:
        name: grafana-server
        enabled: yes
        state: started

...
